# Pytorch

In [1]:
import torch

In [26]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_properties(0))

True
_CudaDeviceProperties(name='GeForce 920M', major=3, minor=5, total_memory=2048MB, multi_processor_count=2)


In [5]:
t1=torch.tensor(4.0)
t1

tensor(4.)

In [6]:
type(t1)

torch.Tensor

In [7]:
t1.dtype

torch.float32

In [9]:
# Float tensor
t2=torch.tensor([1.,2,4,5,3])
t2

tensor([1., 2., 4., 5., 3.])

In [10]:
# Vector tensor
t2.dtype

torch.float32

In [12]:
# Matrix tensor
t3=torch.tensor([[5,6.],[4,7],[9,9]])
t3

tensor([[5., 6.],
        [4., 7.],
        [9., 9.]])

In [14]:
t4 = torch.tensor([[5,6.],[4,7],[9,9,8]])  #this will give error

ValueError: expected sequence of length 2 at dim 1 (got 3)

In [21]:
# 3-D array tensor
t4 = torch.tensor([[[5,3,6],[7,8,9]],[[6,7,3],[2,1,3]]])
t4

tensor([[[5, 3, 6],
         [7, 8, 9]],

        [[6, 7, 3],
         [2, 1, 3]]])

In [15]:
# Shape
t1.shape

torch.Size([])

In [16]:
t2.shape

torch.Size([5])

In [17]:
t3.shape

torch.Size([3, 2])

In [27]:
t4.shape

torch.Size([2, 2, 3])

## Tensor operations and gradients ##

In [11]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)
print(x)
print(w)
print(b)

tensor(3.)
tensor(4., requires_grad=True)
tensor(5., requires_grad=True)


In [12]:
y = w * x + b
print(y)
y.backward()
# print gradients
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

tensor(17., grad_fn=<AddBackward0>)
dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [65]:
# Note donot run above cell more then once, or itwill keep on adding all values

In [77]:
# try it
y = w * x + b
y
y.backward()
# print gradients
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

print("now reset the .grad values for all coz we added it: ")
w.grad.zero_()
b.grad.zero_()
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(6.)
dy/db tensor(2.)
now reset the .grad values for all coz we added it: 
dy/dx None
dy/dw tensor(0.)
dy/db tensor(0.)


# Numpy

In [69]:
import numpy as np

In [70]:
n1 = np.array([[2,5],[4.,9]])
n1

array([[2., 5.],
       [4., 9.]])

In [72]:
# convert numpy array to torch tensor
y = torch.from_numpy(n1) # this method uses the same space of memory
y

tensor([[2., 5.],
        [4., 9.]], dtype=torch.float64)

In [73]:
z = torch.tensor(n1)  # this method creates a copy and take new space
z

tensor([[2., 5.],
        [4., 9.]], dtype=torch.float64)

In [74]:
n1.dtype, y.dtype

(dtype('float64'), torch.float64)

In [76]:
# visa versa: torch tensor to numpy
n2 = y.numpy()
n2

array([[2., 5.],
       [4., 9.]])